senttevaluation/senttevaluation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('senttevaluationapp.urls')),
]

senttevaluation/senttevaluationapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from senttevaluationapp import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
# ----------------------------------  Login ---------------------------------.
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
# ----------------------------------  Administrador ---------------------------------------------.
    path('home', views.admin_inicio, name="home"),
    path('adminAcciones', views.admin_acciones, name="adminAcciones"),
    path('adminAgregarAcciones', views.agregar_acciones, name="adminAgregarAcciones"),
    path('adminAccionesModificar/<id>/', views.editar_acciones, name="adminAccionesModificar"),
    path('adminAccionesEliminar/<id>/', views.eliminar_acciones, name="adminAccionesEliminar"),
    path('adminCargos', views.admin_cargos, name="adminCargos"),
    path('adminAgregarCargos', views.agregar_cargos, name="adminAgregarCargos"),
    path('adminCargosModificar/<id>/', views.editar_cargos, name="adminCargosModificar"),
    path('adminCargosEliminar/<id>/', views.eliminar_cargos, name="adminCargosEliminar"),
    path('adminCompetencias', views.admin_competencias, name="adminCompetencias"),
    path('adminAgregarCompetencias', views.agregar_competencias, name="adminAgregarCompetencias"),
    path('adminCompetenciasModificar/<id>/', views.editar_competencias, name="adminCompetenciasModificar"),
    path('adminCompetenciasEliminar/<id>/', views.eliminar_competencias, name="adminCompetenciasEliminar"),
    path('adminGerencias', views.admin_gerencias, name="adminGerencias"),
    path('adminAgregarGerencias', views.agregar_gerencias, name="adminAgregarGerencias"),
    path('adminGerenciasModificar/<id>/', views.editar_gerencias, name="adminGerenciasModificar"),
    path('adminGerenciasEliminar/<id>/', views.eliminar_gerencias, name="adminGerenciasEliminar"),
    path('adminSubgerencias', views.admin_subgerencias, name="adminSubgerencias"),
    path('adminAgregarSubgerencias', views.agregar_subgerencias, name="adminAgregarSubgerencias"),
    path('adminSubgerenciasModificar/<id>/', views.editar_subgerencia, name="adminSubgerenciasModificar"),
    path('adminSubgerenciasEliminar/<id>/', views.eliminar_subgerencia, name="adminSubgerenciasEliminar"),
    path('adminUsuarios', views.admin_usuarios, name="adminUsuarios"),
    path('adminAgregarUsuarios', views.agregar_usuario, name="adminAgregarUsuarios"),
    path('adminUsuariosModificar/<id>/', views.editar_usuario, name="adminUsuariosModificar"),
    path('adminUsuariosEliminar/<id>/', views.eliminar_usuario, name="adminUsuariosEliminar"),
    path('adminPerfil', views.admin_perfil, name="adminPerfil"),
    path('adminAgregarPerfil', views.agregar_perfil, name="adminAgregarPerfil"),
    path('adminModificarPerfil/<id>/', views.editar_perfil, name="adminModificarPerfil"),
    path('adminEliminarPerfil/<id>/', views.eliminar_perfil, name="adminEliminarPerfil"),
    path('adminArea', views.admin_areas, name="adminArea"),
    path('adminAgregarArea', views.agregar_areas, name="adminAgregarArea"),
    path('adminAreaModificar/<id>/', views.editar_area, name="adminAreaModificar"),
    path('adminAreaEliminar/<id>/', views.eliminar_area, name="adminAreaEliminar"),
    path('adminIndicadores', views.admin_indicadores, name="adminIndicadores"),
    path('adminAyuda', views.admin_ayuda, name="adminAyuda"),
# ----------------------------------  Evaluador ------------------------------------------------------.
    path('evaluadorInicio', views.evaluador_inicio, name="evaluadorInicio"),
    path('evaluadorEvaluacion', views.evaluador_evaluacion, name="evaluadorEvaluacion"),
    path('evaluadorAutovaluacion/<id>', views.evaluador_autovaluacion, name="evaluadorAutovaluacion"),
    path('evaluadorAutovaluacion2/<id>', views.evaluador_autovaluacion2, name="evaluadorAutovaluacion2"),
    path('evaluadorFormulario/<id>', views.evaluador_formulario, name="evaluadorFormulario"),
    path('evaluadorFormulario2/<id>', views.evaluador_formulario2, name="evaluadorFormulario2"),
    path('evaluadorFormulario3/<id>', views.evaluador_formulario3, name="evaluadorFormulario3"),
    path('evaluadorAyuda', views.evaluador_ayuda, name="evaluadorAyuda"),
# ----------------------------------  Colaborador ----------------------------------------------------.
    path('colaboradorInicio', views.colaborador_inicio, name="colaboradorInicio"),
    path('colaboradorAyuda', views.colaborador_ayuda, name="colaboradorAyuda"),
    path('colaboradorAutovaluacion', views.colaborador_autovaluacion, name="colaboradorAutovaluacion"),
# ----------------------------------  Calibrador -----------------------------------------------------.
    path('calibradorInicio', views.calibrador_inicio, name="calibradorInicio"),
    path('calibradorAyuda', views.calibrador_ayuda, name="calibradorAyuda"),
    path('calibradorEvaluaciones', views.calibrador_evaluaciones, name="calibradorEvaluaciones"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

senttevaluation/senttevaluationapp/models.py
from django.db import models
from django.db.models.fields import IntegerField
from django.utils import timezone
from django.db.models.deletion import CASCADE
from django.core.validators import RegexValidator, EmailValidator
from django.contrib.auth.models import User

# Create your models here.

class Gerencia(models.Model):
    NombreGerencia = models.CharField(max_length=50, unique=True ,validators=[RegexValidator(regex=r'^[a-zA-Z]')])

    def __str__(self):
        return self.NombreGerencia

class Area(models.Model):
    NombreArea = models.CharField(max_length=50, unique=True, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    IdGerencia = models.ForeignKey(Gerencia, on_delete=models.CASCADE, default=1)
    
    def __str__(self):
        return self.NombreArea

class SubGerencia(models.Model):
    NombreSubgerencia = models.CharField(max_length=50, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    IdGerencia = models.ForeignKey(Gerencia, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.NombreSubgerencia
    
class Perfil(models.Model):
    NombrePerfil = models.CharField(max_length=50, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    def __str__(self):
        return self.NombrePerfil
        
class Cargo(models.Model):
    NombreCargo = models.CharField(max_length=50, unique=True ,validators=[RegexValidator(regex=r'^[a-zA-Z]')])
    IdPerfil = models.ForeignKey(Perfil, on_delete=CASCADE, default=1)

    def __str__(self):
        return self.NombreCargo

class Empleado(models.Model):
    Rut = models.CharField(max_length=12, null=False, unique=True, validators=[RegexValidator(regex=r'\b\d{1,2}.\d{3}.\d{3}-[K|k|0-9]' )])
    Nombre = models.CharField(max_length=100, null=False, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    FechaIngreso = models.DateField(null=False)
    Correo = models.CharField(max_length=100, null=False, unique=True, validators=[EmailValidator])
    IdPerfil = models.ForeignKey(Perfil, on_delete=CASCADE, default=1)
    user = models.OneToOneField(User, unique=True, null=False, on_delete=CASCADE)
    IdSubGerencia = models.ForeignKey(SubGerencia, on_delete=CASCADE, default=1)
    Imagen = models.ImageField(default="foto_perfil.jpg", upload_to="usuarios", null=True, blank=True)

    def __str__(self):
        return self.Nombre 

class PerfilRol(models.Model):
    Roles = [
        (1, "Evaluador"),
        (2, "Evaluado"),
        (3, "Calibrador"),
    ]
    Rol = models.IntegerField(choices=Roles, default=1)
    RelacionEvaluado = models.CharField(max_length=50, blank=True, default='',validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    NombreEvaluador = models.CharField(Empleado, max_length=100, null=True, blank=True)
    NombreCalibrador = models.CharField(Empleado, max_length=100, null=True, blank=True)
    IdEmpleado = models.ForeignKey(Empleado, on_delete=CASCADE)

    def __str__(self):
        return str(self.Rol)

class Evaluacion(models.Model):
    Estado = models.CharField(max_length=50, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    Fase = models.CharField(max_length=50, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    ComentarioCalibrador = models.CharField(max_length=80,  null=True, blank=True, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    FechaEvaluacion = models.DateTimeField(default=timezone.now)
    ComentarioEvaluador = models.CharField(max_length=100, null=True, blank=True,validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    AutoEvaluacion = models.IntegerField( null=True, blank=True, validators=[RegexValidator(regex=r'^[0-9]')])
    Calificacion = models.PositiveIntegerField( null=True, blank=True, default=1, validators=[RegexValidator(regex=r'^[0-9]')])
    Verificar = models.PositiveIntegerField( null=True, blank=True, validators=[RegexValidator(regex=r'^[0-9]')])
    IdEmpleado = models.ForeignKey(Empleado, on_delete=CASCADE, default=1)

    def __str__(self):
        return self.Fase

class PlanAccion(models.Model):
    Accion = models.CharField(max_length=50, null=True, blank=True, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    Medicion = models.CharField(max_length=50, null=True, blank=True, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    IdEvaluacion = models.ForeignKey(Evaluacion, on_delete=CASCADE, default=1)

    def __str__(self):
        return self.Accion
class DetalleEv(models.Model):
    Notas = [
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5),
        (6,6),
        (7,7),
    ]
    FechaEvaluacion = models.DateTimeField(default=timezone.now)
    ComentarioEvaluador = models.CharField(max_length=100, null=True, blank=True,validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    Calificacion = models.IntegerField(null=True, blank=True, choices=Notas)
    AutoEvaluacion = models.IntegerField(null=True, blank=True, validators=[RegexValidator(regex=r'^[0-9]')])
    Calificacion = models.PositiveIntegerField( null=True, blank=True, validators=[RegexValidator(regex=r'^[0-9]')])
    AutoEvaluacion = models.PositiveIntegerField( null=True, blank=True, validators=[RegexValidator(regex=r'^[0-9]')])
    IdEvaluacion = models.ForeignKey(Evaluacion, on_delete=CASCADE, default=1)
    IdPlanAccion = models.ForeignKey(PlanAccion, on_delete=CASCADE, default=1)

class Competencia(models.Model):
    NombreCompetencia = models.CharField(max_length=60, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    Definicion = models.CharField(max_length=1000, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    IdPerfil = models.ForeignKey(Perfil, on_delete=CASCADE, default=1)

    def __str__(self):
        return self.NombreCompetencia

class AccionClave(models.Model):
    Descripcion = models.CharField(max_length=1000, validators=[RegexValidator(regex=r'^[a-zA-Z]' )])
    IdCompetencia = models.ForeignKey(Competencia, on_delete=CASCADE, default=1)

    def __str__(self):
        return self.Descripcion

class EmpleadoEliminado(models.Model):
    Rut = models.CharField(max_length=12)
    Nombre = models.CharField(max_length=50)
    Correo = models.CharField(max_length=50)
    FechaEliminacion = models.DateField(auto_now=True)

senttevaluation/senttevaluationapp/templates/sidebars/adminSidebar.html
{% load static %}
<!-- Se crea la divicion para el menu lateral -->
<div class="sidebar close">
  <!-- Se configura el logo con el nombre -->
  <div class="logo-details">
    <a class="logo-details" href="/home">
      <i><img src="{% static 'img/logo.png' %}" width="50" height="50"></i>
      <span class="logo_name">Sentte</span>
    </a>
    <i class='bx bx-menu' id="btn" ></i>
  </div>
  <!-- Se realizan las opciones del menu lateral -->
  <ul class="nav-links">
    <!-- Administrador -->
    <li>
        <a href="/home">
          <i class='bx bx-home'></i>
          <span class="link_name">Inicio</span>
        </a>
    </li>
    {% if perms.auth.add_permission %}
    <li>
      <a href="/adminIndicadores">
        <i class='bx bx-bar-chart-square'></i>
        <span class="link_name">Indicadores</span>
      </a>
   </li>
    <li>
        <a href="/adminAcciones">
          <i class='bx bx-task'></i>
          <span class="link_name">Acciones</span>
        </a>
    </li>
    <li>
      <a href="/adminPerfil">
        <i class='bx bx-user-circle'></i>
        <span class="link_name">Perfiles</span>
      </a>
   </li>
    <li>
      <a href="/adminArea">
        <i class='bx bx-aperture'></i>
        <span class="link_name">Areas</span>
      </a>
    </li>
    <li>
        <a href="/adminCargos">
          <i class='bx bx-briefcase-alt'></i>
          <span class="link_name">Cargos</span>
        </a>
    </li>
    <li>
        <a href="/adminCompetencias">
          <i class='bx bx-trophy'></i>
          <span class="link_name">Competencias</span>
        </a>
    </li>
    <li>
      <a href="/adminGerencias">
        <i class='bx bx-street-view'></i>
        <span class="link_name">Gerencias</span>
      </a>
    </li>
    <li>
      <a href="/adminUsuarios">
        <i class='bx bx-user-plus'></i>
        <span class="link_name">Usuarios</span>
      </a>
    </li>
    <li>
      <a href="/adminSubgerencias">
        <i class='bx bx-group'></i>
        <span class="link_name">Subgerencias</span>
      </a>
  </li>   
  {% endif %}
  <!-- Evaluador -->
  {% if perms.senttevaluationapp.view_planaccion %}
    <li>
      <a href="/evaluadorEvaluacion">
        <i class='bx bx-file'></i>
        <span class="link_name">Evaluar</span>
      </a>
    </li>
  {% endif %}
    <li>
      <a href="/adminAyuda">
        <i class='bx bx-donate-heart'></i>
        <span class="link_name">Ayuda</span>
      </a>
    </li>
    <!-- Se crea la visual del perfil abajo del menu -->
    <li>
        <div class="profile-details">
          <div class="profile-content">
            {% if user.is_staff %}
              <img src="/media/foto_perfil.jpg" alt="profileImg" width="52px" height="52px">
            {% else %}
              <img src="/media/{{ request.user.empleado.Imagen }}" alt="profileImg" width="52px" height="52px">
            {% endif %}
          </div>
          <div class="name-job">
            <div class="profile_name">{{ user.username }}</div>
            {% if user.is_staff %}
              <div class="job">{{ request.user.email }}</div>
            {% else %}
            <div class="job">{{ request.user.empleado.Correo }}</div>
            {% endif %}
          </div>
          <i>
            <a class='bx bx-log-out' href="{% url 'logout' %}"></a>
          </i>
        </div>
    </li>
  </ul>
</div>